### ISSUE TITLE
Organizar ejemplos y ejercicios en directorios separados

### ISSUE THREAD

**Issue by ivanhercaz** [makersGC/upython#1]
Si los códigos que se utilizan como ejemplos y para los ejercicios se organizasen en directorios separados estarían más accesibles a aquellos que quieran ir directos a uno concreto; e incluso ejecutarlo si el interesado ha clonado el repositorio. De lo contrario, tendría que buscar en el README lo que le interesa. Además, en el caso de que el README cambie y se sustituyan algunos ejemplos u ejercicios por otros, sus códigos quedarían almacenados en sus respectivas carpetas.

Para ello propongo:

- [ ] Copiar los códigos de los ejercicios a archivos independientes en el directorio `ejercicios`.
- [x] Copiar los códigos de los ejemplos a archivos independientes en el directorio `ejemplos`.
- [ ] Revisar los códigos para ajustarlos al PEP8.

**Comment by kerberosdelhades** [comment]
Me parece una línea de acción más que razonable. Apoyo que sigamos adelante
con ella.
Saludos,

--
Iván Juanes
Profesor de griego

**Comment by ivanhercaz** [comment]
*Ejemplos* migrados y corregidos en su respectivo directorio.
